version: '3.8'
services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: tod
      POSTGRES_PASSWORD: test
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    volumes:
      - "dragonfly_data:/data"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - dragonfly
volumes:
  db_data:
  dragonfly_data:
