version: '3.8'
services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: tod
      POSTGRES_PASSWORD: test
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
volumes:
  db_data:
  redis_data:
