version: '3.8'
services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    volumes:
      - "dragonfly_data:/data"
  minio:
    container_name: minio
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    restart: unless-stopped
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - dragonfly
volumes:
  db_data:
  dragonfly_data:
  minio_data:
